name: fix code styling

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string
      message:
        default: Run php-cs-fixer
        type: string
      fix:
        default: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Laravel Audit
        run: composer global require socoladaica/laravel-audit:^1.3
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }' # [tl! **]

      - name: Run php-cs-fixer
        run: php-cs-fixer --config=/home/runner/.composer/vendor/socoladaica/laravel-audit/.php_cs.php fix

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}
