# https://github.com/marketplace/actions/automatic-releases

name: "Release"

on:
  workflow_call:
    inputs:
      version:
        default: "1.0"
        type: string
jobs:
  release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ inputs.version }}
          prerelease: false
          title: ${{ inputs.version }}
          files: "*"
